title: The GenCC
google_analytics:
text_footer: The information on this website is not intended for direct diagnostic use or medical decision-making without review by a genetics professional. Individuals should not change their health behavior solely on the basis of information contained on this website. The GenCC does not independently verify the submitted information.  Though the information is obtained from sources believed to be reliable, no warranty, expressed or implied, is made regarding accuracy, adequacy, completeness, reliability or usefulness of any information. This disclaimer applies to both isolated and aggregate uses of the information. The information is provided on an “as is” basis, collected through periodic submission and therefore may not represent the most up-to-date information from the submitters. If you have questions about the information contained on this website, please see a health care professional.

seo_default_desc: The information on this website is not intended for direct diagnostic use or medical decision-making without review by a genetics professional. Individuals should not change their health behavior solely on the basis of information contained on this website. The GenCC does not independently verify the submitted information.  Though the information is obtained from sources believed to be reliable, no warranty, expressed or implied, is made regarding accuracy, adequacy, completeness, reliability or usefulness of any information. This disclaimer applies to both isolated and aggregate uses of the information. The information is provided on an “as is” basis, collected through periodic submission and therefore may not represent the most up-to-date information from the submitters. If you have questions about the information contained on this website, please see a health care professional.

url: http://scottgoehringer.com/gencc-static-test/
url_members: members.html
url_about: about.html
url_articles: articles.html

theme_remote: sgoehringer/gencc-static-test

collections:
  members:
    output: true
    show_status: true
  articles:
    output: true
    show_status: true
  leadership:
    output: true
    show_status: true
  projects:
    output: true
    show_status: true